package com.sah.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "sah")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idArea;
	private String nombre;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Area() {
	}

	public Area(String nombre) {
		this.nombre = nombre;
	}

	public Area(String nombre, Set<Empleado> empleados) {
		this.nombre = nombre;
		this.empleados = empleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idArea", unique = true, nullable = false)
	public Integer getIdArea() {
		return this.idArea;
	}

	public void setIdArea(Integer idArea) {
		this.idArea = idArea;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@JsonBackReference("empleados")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
